### ISSUE TITLE
ANE crashes when the app loses focus while a download is in progress

### ISSUE THREAD

**Issue by matyasatfp** [myflashlab/downloadManager-ANE#8]
As in title, on a Nexus 4 with Android 5.1.1.

Steps to reproduce:  
1. start a long download.
2. While its downloading switch away from the app

AS3 code:
var _ex:DM = new DM();
        _ex.addEventListener(DMEvent.ERROR, onDownloadTaskError);
        _ex.addEventListener(DMEvent.PROGRESS, onDownloadTaskProgress);
        _ex.addEventListener(DMEvent.COMPLETE, onDownloadTaskCompleted);
        setTimeout(function():void{ // just for testing, to have time to dismiss alert
            _ex.startDownload(updateLocation,  File.applicationStorageDirectory.nativePath, "assets.zip");
        }, 4000);

Logcat:
```
01-29 16:44:48.343 10183-10353/? E/AndroidRuntime: FATAL EXCEPTION: Thread-4054
                                                   Process: air.com.test.testApp, PID: 10183
                                                   java.lang.IllegalArgumentException
                                                       at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
                                                       at com.doitflash.downloadManager.AirCommand.onDownloadProcess(AirCommand.java:347)
                                                       at com.doitflash.downloadManager.report.listener.DownloadManagerListenerModerator.onDownloadProcess(DownloadManagerListenerModerator.java:28)
                                                       at com.doitflash.downloadManager.core.chunkWorker.Moderator.process(Moderator.java:165)
                                                       at com.doitflash.downloadManager.core.chunkWorker.AsyncWorker.process(AsyncWorker.java:124)
                                                       at com.doitflash.downloadManager.core.chunkWorker.AsyncWorker.run(AsyncWorker.java:82)
```

**Comment by myflashlab** [comment]
have you tried to pause the download in Air ```Event.DEACTIVATE``` event?
